### ISSUE TITLE
Parsing error when using French langage OS

### ISSUE THREAD

**Issue by EPeillard** [ar-tracking/UnityDTrackPlugin#1]
### Error
When using a French OS, Unity raise the following error: 

> Error parsing line: 6d 1 [17 1.000][162.412 160.040 640.677 -167.6712 -83.7049 91.2583][-0.002408 -0.981364 -0.192145 -0.109623 -0.190728 0.975503 -0.993970 0.023412 -0.107121]

### Fix
In the file Body6DofParser.cs, line 62, the function `Convert.ToString` is missing the second argument `CultureInfo.InvariantCulture`.

**Comment by sk-ART** [comment]
Thank you, Etienne!
