### ISSUE TITLE
Error parsing line

### ISSUE THREAD

**Issue by mbehr068** [ar-tracking/UnityDTrackPlugin#3]
The Camera is working fine, but if I try to ad the Flystick script to a controller I recieve this error when going into play-mode.
I've seen the past issue, but this could not fix it.

Error parsing line: 6df2 2 2 [0 1.000 4 2][1157.327 437.914 653.582][0.160277 0.837277 0.522760 -0.986406 0.155321 0.053661 -0.036267 -0.524254 0.850789][0 0.00 0.00] [1 -1.000 0 0][0.000 0.000 0.000][0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000][]

**Comment by ka-ART** [comment]
Ok, thanks.

Please note that a line like this could be sent by DTrack, if there exists a Flystick ID without assigned radio device (i.e. model / serial). Nevertheless we will fix the parsing error with the next release.

**Comment by ka-ART** [comment]
Fixed with recent commit.
