### ISSUE TITLE
Source has no meta files

### ISSUE THREAD

**Issue by iLinaza** [ar-tracking/UnityDTrackPlugin#4]
We would like to use UnityDTrackPlugin as a package. For this purpose, we have sent the request to OpenUPM to be published in their registry (https://openupm.com/packages/com.art.dtrack).

When trying to import the package into Unity we encounter the issue that the source files do not have .meta files and therefore Unity ignores them (error: Asset Packages/com.art.dtrack/Scenes/DTrackExample.unity has no meta file, but it's in an immutable folder. The asset will be ignored).

In case it could speed up the process, I could do a PullRequest with the missing meta files.

**Comment by ka-ART** [comment]
All (necessary) meta files are part of the ready-to-use Unity packages available at [GitHub releases](http://github.com/ar-tracking/UnityDTrackPlugin/releases). But yes, it makes sense to add them to the sources to fit to the OpenUPM automatic build pipeline.

Please note that the plugin will also be available in the Unity Asset Store soon.

**Comment by bdominguez** [comment]
@ka-ART is more convenient to install as a package because of the advantages over the old Unity format of the Asset Store (*.unitypackage): no third party code in /Assets, easy version change, etc...

To unblock this problem we simply need the meta files to be generated, nothing else.

@ka-ART you take care of it or we create a PR?

Thanks!

**Comment by ka-ART** [comment]
That's true, but most people are searching the Unity Asset Store first.

We will add the meta files soon. And thanks, it's a good idea to have the OpenUPM way as an additional option to install the plugin!

**Comment by bdovaz** [comment]
@ka-ART Any news? Thank you.

**Comment by ka-ART** [comment]
We're on it, but there are more issues related to it. Meanwhile use the 'old-fashioned' custom Unity package.

**Comment by iLinaza** [comment]
Please note that, in addition to adding .meta files, it is also necessary to include an Assembly Definition file so DTrack plugin can be used as a package.

**Comment by ka-ART** [comment]
Fixed with recent commit.

Please note that we renamed the package into 'com.ar-tracking.dtrack' to coincide with our web domain. A pull request in openupm/openupm was already created to adjust the registry.
