### ISSUE TITLE
DTrack 1 with the Plugin emtpy frames and errors , simple bugfix

### ISSUE THREAD

**Issue by TUCDeveloper** [ar-tracking/UnityDTrackPlugin#6]
Dear ART team,
We are currently experimenting with the DTrack 1 and the Unity plugin. Unfortunately, the received output data could not be read by the current plugin. There were always empty frames or the casting of the ASCII string did not work. 
After a long search I was able to find the error:

In the file BodyParser.cs the received string is split and stored in float variables. In the last matrix for rotation, a ] always ends up in the variable. The reason for this is that DTrack1 adds a space after the ] in the output and then adds \r\n. When parsing, this goes wrong and a hidden casting error occurs, which makes the frame appear empty. (In DTrack2 the space doesnt exist)

My simple workaround is that before line 76 BodyParser.cs

`float r8 = Convert.ToSingle( r[ 8 ], CultureInfo.InvariantCulture );`

insert another one: 
`r[8] = r[8].Remove(r[8].Length - 1);`

this removes the ] and the subsequent casting works without any problems.

Best

**Comment by ka-ART** [comment]
Dear TUCDeveloper,

thanks for the hint and your effort to identify the problem! To be honest we didn't expect that someone would use the plugin with the really old DTrack1 (last version was released in 2009)... Nevertheless we'll provide a fix with the next release of the plugin.
