### ISSUE TITLE
Please verify on 2022.3.X and indicate if it works on all platforms Unity supports.

### ISSUE THREAD

**Issue by RubenGarcia** [ar-tracking/UnityDTrackPlugin#7]
I will add in this ticket my experience with 2022.3.X.

**Comment by ka-ART** [comment]
Hi Ruben,

we're a bit surprised, could you specify which problems you encounter on which platforms? We tried the most recent Unity 2022.3.24f1 on Windows and Linux, and couldn't see any problems.

Regards,
Kurt

**Comment by RubenGarcia** [comment]
I did not find any problems, the code works for me as well on 2022.3.
But
https://github.com/ar-tracking/UnityDTrackPlugin
Readme.md indicates
Validated with Unity Editors 2019.4 to 2022.2
so if this has been tested on 2022.3, I´d like it to be changed to
Validated with Unity Editors 2019.4 to 2022.3
I can make the merge request with the change if you prefer.

**Comment by RubenGarcia** [comment]
I just wanted to know if 2022.3 was officially supported or not.

**Comment by RubenGarcia** [comment]
https://github.com/ar-tracking/UnityDTrackPlugin/pull/8

**Comment by ka-ART** [comment]
We merged your pull request, thanks.
Although as I understood the Unity version numbering, increasing minor numbers 2022.X are indicating the hardening of a release, not versions with different features. So actually any Unity with higher minor numbers (as the verified 2022.2) should automatically support the plugin.
